### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by TheDabblingDuck** [Yutsuten/anki-lifedrain#103]
Hi, thanks for writing this addon. I really like it but I'm trying to run Anki on a really low end windows machine and enabling this addon causes really high CPU usage. Normally Anki drops down to 0% CPU usage when idle but with this addon Anki CPU usage is constantly elevated, and eventually Anki starts lagging to the point of being unusable. Any idea why this might be happening?

**Comment by Yutsuten** [comment]
Thank you for reporting this issue!
I'll need some more information before I can start looking for the cause of the problem.

1. Can you tell me if the issue only happens while reviewing, or all the time?
2. Could you take a screenshot of the CPU usage of Anki while the add-on is enabled?
3. Disabling the add-on using the add-on's global settings change anything?

**Comment by TheDabblingDuck** [comment]
I can't seem to recreate CPU usage as high as it was that day, so I'll just close this.
