### ISSUE TITLE
Deactivates "l" as an answer button

### ISSUE THREAD

**Issue by joepusey1-alt** [Yutsuten/anki-lifedrain#108]
2.1.26 OS Catalina 10.15.5

When the add-on is enabled, Anki no longer recognises my pressing "l" as an answer button (the third button along the bottom. I guess this means that your add-on isn't compatible with Right Hand Reviews jkl, the add-on that normally allows me to do this? Please let me know if this is fixable because I really love both add ons :)

**Comment by Yutsuten** [comment]
Thank you for using Life Drain!

Yes, there is a way to change the shortcut. You can see how [here](https://github.com/Yutsuten/anki-lifedrain/wiki/Changing-Shortcut-Keys).
By the way, the next release I plan to add a way to change the shortcuts within the Settings dialog! See #107.

**Comment by joepusey1-alt** [comment]
Superb, thank you so much- problem solved!
