### ISSUE TITLE
Allow configuring the default initial life to 0

### ISSUE THREAD

**Issue by mighele** [Yutsuten/anki-lifedrain#109]
The way I use Life drain is the opposite way it was intended, but it works brilliantly.

I start with my Current life set to zero and every time I do a rep the life bar increases slightly. Instead of reviewing until my life has drained away, I do it the other way round where I review until I have reached the end. It's kind of like a race to the finish type of thing. I have to keep up my speed because the bar gradually drains so I'm sort of racing against the bar draining.

I notice you have recently added the Recover button which resets the Current life to equal Maximum life. However, resetting Life Drain for me involves setting Current life to 0. **Would it be possible to add this feature so that the Recover button can function in either mode?**

Thanks
Mike

**Comment by Yutsuten** [comment]
That's an interesting way to use Life Drain.
I'll think on a way to make that possible. Thank you for the suggestion!
