### ISSUE TITLE
Undo life drain broken on 2.1.46/V3 scheduler

### ISSUE THREAD

**Issue by Helicle** [Yutsuten/anki-lifedrain#114]
Hey Yuksuten,

On Anki 2.1.46, V3 scheduler, Undoing the answering of a card no longer removes that card's life/time addition (Undo behavior is set to Life Drain in the config). This means if you undo a card and answer again, you're effectively getting twice the life bonus from one card.

**Comment by Yutsuten** [comment]
Thank you for reporting the bug!

I'll fix it as I find some free time (lately I'm quite busy...)
