### ISSUE TITLE
Enable Life Drain toggle via Global Settings

### ISSUE THREAD

**Issue by akavi1** [Yutsuten/anki-lifedrain#128]
Pressing Ctrl+L (global settings shortcut) should open the global settings page even if the "Enable Life Drain" box is unchecked, as long as the addon is enabled in Tools>Add-ons.
It's weird that you can use Global Settings to disable the addon but not re-enable it.

**Comment by Yutsuten** [comment]
This behaviour is intended. If disabling the addon, everything should be disabled, including shortcuts.

> Open the Add-ons dialog, select Life Drain, then click the button Config

[Global Settings wiki](https://github.com/Yutsuten/anki-lifedrain/wiki/Global-Settings)

**Comment by akavi1** [comment]
oh ok. I thought it was weird that it's easy to disable but requires more steps to re-enable. But if its intended, that's fine
