### ISSUE TITLE
Option to make bar move Left to Right

### ISSUE THREAD

**Issue by akavi1** [Yutsuten/anki-lifedrain#148]
Would love to see a config option to make the bar move in the opposite direction from what it is currently set as. I read my cards from left to right so it would be nice if the bar moved in the same direction as my eyes. Requires less visual processing.

**Comment by Yutsuten** [comment]
Not sure if I understand your feature request.

Now the bar goes like this:

```
|##########################| Full HP
|#####################-----| Lost 5 HP
|################----------| Lost 10 HP
```

Do you mean something like this?

```
|##########################| Full HP
|-----#####################| Lost 5 HP
|----------################| Lost 10 HP
```

**Comment by akavi1** [comment]
yes, exactly

**Comment by Yutsuten** [comment]
I'll check if it is possible to add this. But this is low priority, so it may take some time.
