### ISSUE TITLE
Bug when suspending/burying cards associated with this addon

### ISSUE THREAD

**Issue by SoftSalem** [Yutsuten/anki-lifedrain#149]
**Anki version & Operating System:** 
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10

**Describe the bug:** 
Whenever I try to suspend or bury a card using the "show more" button of the reviewing window (not a shortcut, only that way), this message is shown on my screen, I discovered that this addon was the responsible of it because I disabled every one I have until the one causing this bug was discovered:

_Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-17 11:41:44

Caught exception:
Traceback (most recent call last):
  File "decorator", line 231, in fun
  File "decorator", line 203, in fix
  File "inspect", line 3043, in bind
  File "inspect", line 2964, in _bind
TypeError: too many positional arguments_

![image](https://user-images.githubusercontent.com/104769180/190872726-cfef5a62-6da0-45ad-a551-415f86e5b3be.png)

**Comment by Yutsuten** [comment]
Good job on finding out the bug, finding out that my addon was the culprit, and by making your way to report it here. Often anki tells what addon is on the blame, but it wasn't the case here. Thank you very much!

I fixed and released a fix now. It is working for me, but in case the bug still happens to you, please reply.

Thank you again!!
