### ISSUE TITLE
latest update of lifedrain not compatible with anki version Version ⁨2.1.65 (aa9a734f)⁩

### ISSUE THREAD

**Issue by howmanychicken** [Yutsuten/anki-lifedrain#160]
I cannot use this add-on anymore because an error comes up when starting anki with it. only goes away if add-on is disabled. very sad because this was an amazing add-on. older version of add-on worked fine with this version of anki on windows. please fix.

**Anki version & Operating System:** 
Version ⁨2.1.65 (aa9a734f)⁩, windows

**When does the crash happens?** 

**Traceback:**

**Comment by Yutsuten** [comment]
I'm very sorry about that. The error does not appear to me, could you give me more details about it? Like the trackeback.

**Comment by Yutsuten** [comment]
OK, I was able to reproduce the issue. It only happens when downloading the code from AnkiWeb. The code is exactly the same, but the `meta.json` being different is making the startup run differently too.

With the `meta.json` downloaded from AnkiWeb I can see the erros, and I'm fixing now.

**Comment by Yutsuten** [comment]
I think I've got it fixed. Could you check the new update and tell me if its working now, please?

**Comment by howmanychicken** [comment]
Yes, working now, thank you so much!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by akavi1** [comment]
This update breaks the addon on Mac. Every time a card is rated, a "processing" bar shows up that takes ~5min to complete

**Comment by Yutsuten** [comment]
@akavi1 Sorry about that. There is no error? Could you get me a screenshot so I can see what you're talking about?

I haven't implemented any progressing bar while reviewing, thats strange...

In the worst scenario, I will need you to debug it with me.

**Comment by akavi1** [comment]
It looks like this. No error messages. The blue bar just moves back and forth for 1-5min then the next card shows up. My guess is that whatever calculations Life Drain is doing is taking far too long to calculate. It's definitely coming from this addon. And I tried on different decks with different numbers of cards. It's the same problem everywhere.

![image](https://github.com/Yutsuten/anki-lifedrain/assets/55925875/1013c79a-eb8b-4577-a9b1-a0871aae9945)

**Comment by akavi1** [comment]
The only way to exit this is to Force Quit the Anki app and restart. Disabling the addon fixes the problem.

**Comment by Yutsuten** [comment]
@akavi1 your issue is different that the one reported by the OP in this issue, so I created #164 

Lets talk there.
