### ISSUE TITLE
Pre-release beta Anki 23.10 opens a lot of error windows and crashes Anki

### ISSUE THREAD

**Issue by shigeyukey** [Yutsuten/anki-lifedrain#166]
**Describe the bug:** 

Pre-release beta Anki 23.10 opens a lot of error windows and crashes Anki.
I fixed it this way to stop the error for now.

**progress_bar.py line137**

**before**
            self._mw.setDockNestingEnabled(enabled=True)
**after**
            self._mw.setDockNestingEnabled(True)

![image](https://github.com/Yutsuten/anki-lifedrain/assets/124401518/dc1afa52-f334-4d86-9a05-11d1ccdb5cac)

**Caught exception:**

Version ⁨23.10 (1f6938d7)⁩
Python 3.9.15 Qt 6.5.2 PyQt 6.5.2

Caught exception: Traceback (most recent call last): File "aqt.taskman", line 138, in _on_closures_pending File "aqt.taskman", line 82, in File "aqt.taskman", line 102, in wrapped_done File "aqt.operations", line 127, in wrapped_done File "aqt.deckbrowser", line 130, in File "aqt.main", line 1217, in onOverview File "aqt.main", line 713, in moveToState File "_aqt.hooks", line 4886, in call File "C:\Users\shigg\AppData\Roaming\Anki2\addons21\715575551\main.py", line 52, in gui_hooks.state_will_change.append(lambda *args: lifedrain.screen_change(args[0])) File "C:\Users\shigg\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 175, in screen_change self.deck_manager.update() File "C:\Users\shigg\AppData\Roaming\Anki2\addons21\715575551\deck_manager.py", line 48, in update self._update_progress_bar_style() File "C:\Users\shigg\AppData\Roaming\Anki2\addons21\715575551\deck_manager.py", line 214, in _update_progress_bar_style self._progress_bar.dock_at(conf['barPosition']) File "C:\Users\shigg\AppData\Roaming\Anki2\addons21\715575551\progress_bar.py", line 137, in dock_at self._mw.setDockNestingEnabled(enabled=True) TypeError: setDockNestingEnabled() takes no keyword arguments

**Comment by shigeyukey** [comment]
Oops my apologies. The problem did not occur only with this add-on, so I think it is interference with some other add-ons.

**Comment by Yutsuten** [comment]
Yeah, when it comes to keeping compatibility with other add-ons, its becomes wild. Anki allows monkey patching, so anyone can make the mess they want.

As you noticed already, I won't be changing my code just because someone else is messing with Anki's code.

And for the reason I'll keep the keyword argument, it's because I want to follow [ruff](https://docs.astral.sh/ruff/rules/) rules as much as possible. Good practices.

Thanks for reporting the issue anyway! Now I'm aware of some messy add-ons.
