### ISSUE TITLE
Allow creating a timer for pomodoro and a timer for life drain at the same time

### ISSUE THREAD

**Issue by NicolasCuri** [Yutsuten/anki-lifedrain#21]
Maybe for future updates, creating a timed session (e.g. 25min) would make sense in order to use life drain as a life bar (e.g. 120s life 5s reviver) inside a session. I think that would be a whole new approach to gamification in Anki. Maybe use some inspiration from this addon: https://ankiweb.net/shared/info/1608644302

I’ve posted about the possibility of your addon as a Pomodoro timer on Reddit, and people loved it. Looking forward to it!

**Comment by NicolasCuri** [comment]
Being able to create a session of 25min and also use the life bar as a pace bar, not as a timer. The life bar would be running as normal (120s 5s), but it would be a timed session so you know when you’ll rest. Got it? Not the statistics..

**Comment by Yutsuten** [comment]
I mentioned the statistics because of the link you sent me, sorry.

Did you mean the long rest after 4 sessions? That is possible with lovac42's script. And even without script its perfectly possible to manage it by yourself.
Or do you mean a clock? You can do it, set `Text` in `Preferences` to `mm:ss`.

If you didn't mean any of those, still didn't got what you want to say.

**Comment by Yutsuten** [comment]
Oh, maybe I got it now. You mean to use both at the same time.

**Comment by Yutsuten** [comment]
Looks complicated to implement, but I'll think about it.

**Comment by NicolasCuri** [comment]
This is how I envision this:

1) First, [click "start study" on your selected deck](https://imgur.com/a/0VK3TTJ) and [choose your preferred time session](https://imgur.com/a/C5UBouY) (customizable. rest period is by default 1/5 of the work period with Pomodoro. A classic one is 25 work - 5min rest).
2) [Use the Pomodoro timer on the bottom-left of Anki to know how much time you have left for the spurt you're having, while using Life Drain as a pacemaker (120s max - 5s recover).](https://imgur.com/a/QrmhcrB) 
(3) After your work time is done, [take a rest and restart after it.](https://imgur.com/a/j5MpXuV) (rest time = 1/5 of work time)
(4) In case you reach life 0 inside a session, introduce the "Game Over" concept, or start a rest period, to gamify and keep you motivated not to fail life drain.

This is how I see this. :)

**Comment by Yutsuten** [comment]
Your idea is cool, really.

If I had the time to implement it, I would. Sadly, I don't.

Being direct: what you're asking isn't a new feature to Life Drain. It is a new add-on. An add-on used with Life Drain, and with some cool integration (Game Over).

There's a thing I want to follow in the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) as a developer: "Do one thing, and do it well." My objective with this add-on is to create a nice Life Drain. No more, no less.

I'm really sorry for it, but as it isn't something I'll work on, I'll close this issue.
