### ISSUE TITLE
Background color of the life drain bar and Night-mode

### ISSUE THREAD

**Issue by NicolasCuri** [Yutsuten/anki-lifedrain#22]
Hey, man! I have a small suggestion:

Is it possible to make an automatic change in the background color when I toggle my night mode? This way I don't have to change the background color of my life drain bar every time I toggle night mode on.

Image demonstrating: https://imgur.com/a/OGvqCjA

What do you think? Or should I ask this to the owner/developer of the Night-mode add-on? Thanks! :)

**Comment by NicolasCuri** [comment]
By the way, I'm using the background colors:

#F0F0F0 ⇒ Normal
#444444 ⇒ Night mode

**Comment by Yutsuten** [comment]
Changing your request a little, but if we change our focus from Night Mode to simply the window's background color, an option to sync the window's color with the bar's background color sounds better.

**Comment by NicolasCuri** [comment]
Hahaha, my bad! I'm a medical student, and I've been using Anki for >6h/day consistently for ~1year now. It is my main source of knowledge acquisition, so I use it a lot, and changing my study environment keeps me motivated to go through a shit ton of reviews (today I have 1600 cards to go through - my cards accumulated due to med school duties). Changing manually is not a problem at all, but since Night Mode is one of the most popular add-ons out there, this can make things aesthetically and functionally better, imho. Thanks for considering my request, you've been extremely helpful to me and to my productivity.

**Comment by Yutsuten** [comment]
Oh I see...

Changing automatically would really be nice, but to what color? Night Mode's color can be changed. Adding a new menu asking for a bar background color when Night Mode is installed AND on doesn't sound good for me.

Are you nice with the modification I wrote earlier? About an option to sync the bar's background color with the window's color.

**Comment by NicolasCuri** [comment]
I think these would be nice:

#F0F0F0 ⇒ Normal (default)
#444444 ⇒ Night mode.

Linking the background color of the bar with the window's color (background color of a card) doesn't seem like a good idea since I know lots of people that have shared decks with different card stylings. So they would have their bars changed every time they have a card with a different styling. 

I don't want to waste your time; it is just a small suggestion to consider! :)

**Comment by Yutsuten** [comment]
You're misunderstanding the meaning of window's color. It is NOT the background color of a card. Or else installing Night Mode wouldn't be necessary, just set the background of the card to the color you want. You certainly know the card's background color has a much more limited area.

Anyway, we're thinking on the same thing and explaining with different words. I'm just being more generic.
I'll see what I can do about it.

**Comment by NicolasCuri** [comment]
Ha! Ok! My bad :) Looking forward to it.
