### ISSUE TITLE
Color Bar Issue

### ISSUE THREAD

**Issue by jedens10** [Yutsuten/anki-lifedrain#30]

**Comment by jedens10** [comment]
Great work Yutsuten, however, I seem to be having a problem. I went into the life drain preferences tab to change the foreground and background colors. Unfortunately, when I go to change one, it changes them all to the same color every time I close the preferences window. As a result, I now can no longer differentiate between the progress bar's foreground and background. I've tried deleting and reinstalling the add-on and updating to the newest version of anki. Either way, it didn't revert to the addons default color settings.

**Comment by jedens10** [comment]
![image](https://user-images.githubusercontent.com/48512202/54267464-81d0b500-4536-11e9-8f56-15d42daf2c10.png)

Also, the "background color" button is always selected for me. Any ideas?

**Comment by Yutsuten** [comment]
This issue is probably related to your OS...

So let me see if I understood. This is not the first time you install the add-on, so it already worked for you, but don't work anymore?
While editing, you do can choose different colors. But if you close and open again, it is all equal again. If you choose red to background, green to foreground and blue to text, which color it becomes after reopening the settings? Have you tried editing it, and without opening the settings again, check if the bar has the correct colors?

I'll have a look on the code later, but honestly I have no clue of what could be the problem...
Can you tell me the release/version of your Mac? This information may help me to find the issue.

**Comment by jedens10** [comment]
Thanks for the quick reply. Yes, it was previously working as intended prior to me trying to change the progress bar colors. 
As soon as I close the preferences for the changes to take effect, all the colors become equal as can be seen when I immediately then start a study session. 
I'm running Mac OS 10.14, but honestly, if nobody else is having the issue it is likely not worth your time. 
After making my original post, I discovered I can change the "style" of the bar and the add-on regains its functionality. I have still lost the ability to choose foreground/background colors, but I care very little about the aesthetics when compared to function.

**Comment by Yutsuten** [comment]
I'm willing to fix this, even if it only affects a small percentage of the users. For that I'll need your help, as I can't reproduce this bug neither in Linux nor in Windows. I don't have a Mac.

> After making my original post, I discovered I can change the "style" of the bar and the add-on regains its functionality.

Good to know! I was worried that you wouldn't be able to use my add-on anymore.

As soon as I find some time, I'll look for a solution. Any update I'll write here!

**Comment by TheMedicalStudent** [comment]
Hi I just made an account here to let you know that I am having the exact same issue as this person, and I tried all the same troubleshooting steps. Let me know if there is any way I can help resolve it.

**Comment by Yutsuten** [comment]
@TheMedicalStudent Is your PC a Mac OS 10.14 too?

**Comment by TheMedicalStudent** [comment]
> @TheMedicalStudent Is your PC a Mac OS 10.14 too?

Yes MacOS Mojave 10.14.4

**Comment by 10654023** [comment]
Same exact issue with the colors. Mac Os 10.14.4. So sad this isn't working. Such a cool add-on. Really appreciate your work.

**Comment by 10654023** [comment]
I'm a med student and would really appreciate any help on this. Helps me stay focused during the monotony.

**Comment by TheMedicalStudent** [comment]
Additionally it seems like all the settings get reset every time the Anki app is restarted.

**Comment by Yutsuten** [comment]
> Additionally it seems like all the settings get reset every time the Anki app is restarted.

@TheMedicalStudent This issue sounds to be unrelated to the bar color's bug. If you really have this problem, probably it is better to open another issue with more details in it, like your OS, Anki version and ways to reproduce.

And if the problem really exists, it is related to your OS, as it does not occur for me. By the way, I'm using Debian + Anki 2.0.52.

**Comment by Yutsuten** [comment]
I've found an option to disable the native color dialog. Could someone with a Mac follow this steps?

1. Open my script in an editor or on Anki
2. Add [this change](https://github.com/Yutsuten/anki-lifedrain/commit/05207206896eb8a9ed386da741d5ec88f1e7767a)
3. Restart Anki
4. Check if it solves the problem and report the results here

I've found that the Color Dialog in Mac is a little buggy, so there is a chance that this will solve the problem.

**Comment by TheMedicalStudent** [comment]
> I've found an option to disable the native color dialog. Could someone with a Mac follow this steps?
> 
> 1. Open my script in an editor or on Anki
> 2. Add [this change](https://github.com/Yutsuten/anki-lifedrain/commit/05207206896eb8a9ed386da741d5ec88f1e7767a)
> 3. Restart Anki
> 4. Check if it solves the problem and report the results here
> 
> I've found that the Color Dialog in Mac is a little buggy, so there is a chance that this will solve the problem.

This appears to have fixed the issue for now. My changes to the color options now work as they should, but it remains to be seen if it stays that way when I close/open Anki. I'll continue tinkering with it and update you with the results, thanks!

**Comment by MedAnki** [comment]
Hey man! I love the concept of Life Drain. Even I have been having the same problem. I tried to change the colour bar but it would won't do and get stuck on all blues for me.

I have a MacBook, running Mojave 10.14.1
Anki Version 2.1.11

I will also try to follow the solution given above and give you my observations accordingly.

Good job on all the work!

**Comment by MedAnki** [comment]
So, the change worked but not completely. I was able to change the colours only in DEFAULT option in STYLE, I was able to choose all other options in STYLE but they all showed the same style(shown below).
<img width="423" alt="image" src="https://user-images.githubusercontent.com/42865576/56680354-bebaca80-66e4-11e9-9d90-505bc166b4e8.png">


This style
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/42865576/56680405-d2fec780-66e4-11e9-861d-e2b0b3740638.png">


But when I used to choose DEFAULT, then I can change the colours.

**Comment by MedAnki** [comment]
> This style

The blue bar.
The green one is PROGRESS BAR add-on.

**Comment by Yutsuten** [comment]
> I was able to change the colours only in DEFAULT option in STYLE, I was able to choose all other options in STYLE but they all showed the same style

That is expected. That's how custom styles works, the color support only works fully on the default option.
Thank you for the feedback!
