### ISSUE TITLE
[Suggestion] Add win noise when there are no more cards to review

### ISSUE THREAD

**Issue by paanvaannd** [Yutsuten/anki-lifedrain#31]
The addition of a "Success" noise +/- animation would be a good positive reinforcement tool for completing a deck, in my opinion. When Life Drain is running and there are no more cards left to review, play the sound file.

**Comment by Yutsuten** [comment]
This suggestion sounds like another add-on for me. Independently of being a Life Drain user, people may want such feature.

I searched a little, there are some already done add-ons that are related to what you're looking for.
- [Kitten Rewards (Gamification)](https://ankiweb.net/shared/info/1627107763)
- [reward sound](https://ankiweb.net/shared/info/1165586281)
- [Anki Fanfare (Gamification/Feedback)](https://ankiweb.net/shared/info/2073603704)

I haven't tried any of them, but if you have interest, it may worth a try.

About creating the add-on you want exactly as you wrote here, I have no time nor interest to it.
I'm even struggling to find time to fix [this](https://github.com/Yutsuten/anki-lifedrain/issues/30)...

**Comment by paanvaannd** [comment]
I already tried some of those add-ons, but wasn’t aware of the Reward Sound; thanks!

I actually wanted to use this feature alongside Kitten Rewards because that one doesn’t play sounds, only displays images.

I agree that it would probably be another add-on for the reason you stated. Or, since Kitten Rewards already does something similar, perhaps I’ll post a request to its author or try my hand at it when I have more time.
