### ISSUE TITLE
When loading 'Life Drain' Error

### ISSUE THREAD

**Issue by Kosezu** [Yutsuten/anki-lifedrain#37]
When loading 'Life Drain':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/715575551/__init__.py", line 4, in <module>
    from . import lifedrain  # pylint: disable=unused-import
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/715575551/lifedrain.py", line 789, in <module>
    import Night_Mode
  File "/Users/csosborn/Library/Application Support/Anki2/addons21/Night_Mode.py", line 99, in <module>
    nm_default_css_top = mw.toolbar._css
AttributeError: 'Toolbar' object has no attribute '_css'

**Comment by Yutsuten** [comment]
The error is when importing Night Mode...
Did you upgraded Night Mode recently? Seems like a change there broke Life Drain.

**Comment by Yutsuten** [comment]
To be honest, this feels more a Night Mode bug than a Life Drain bug, even though I can fix from my side.

**Comment by Yutsuten** [comment]
https://github.com/Yutsuten/anki-lifedrain/blob/ebe5a43c6031f8fc786fa9efc516cf663570d1d6/src/lifedrain/lifedrain.py#L788-L792

At line 791, can you change `except ImportError:` to `except Exception:` to see if it solves the problem in Life Drain?

**Comment by Kosezu** [comment]
I'm on the most recent version of Night Mode that's up on Add-ons for Anki 2.1

**Comment by Kosezu** [comment]
I made the edit; no longer get the error. Did that disable night mode for Life Drain?

**Comment by Yutsuten** [comment]
No, it only ignores the error.

**Comment by Kosezu** [comment]
Thank you for the quick fix!
