### ISSUE TITLE
Feature Request: Smooth Bar Animation

### ISSUE THREAD

**Issue by Krakyn** [Yutsuten/anki-lifedrain#39]
Hey! Thanks for making this addon, I find it really useful.

Is there any way you could make the bar drain smoothly? What I mean is continuous movement, rather than losing 'chunks' one second at a time? This would look really incredible.

**Comment by Yutsuten** [comment]
I agree, and that's what I tried to do from the very beginning, but it didn't work. Seems to be an limitation of the QProgressBar of the Qt library.

As far as I remember, it always round the bar to the nearest integer. For example, if the life is 87.8%, it will round to 88%. So even if I reduce the interval between drains and remove 0.1% of the life each interval, there will be no bar movement most of the time.

If you know any workaround, please tell me!

**Comment by Yutsuten** [comment]
The first time I tried it was on Qt 4, now on Anki 2.1 they use Qt 5 and maybe it works. I'll give it a try!
