### ISSUE TITLE
Improvement for the "Life Drain"

### ISSUE THREAD

**Issue by niku-pal** [Yutsuten/anki-lifedrain#46]
Great addition, you are just a god to me!!!

It would be great to add another improvement in this regard, namely:
The same decreasing life bar, which will have a certain maximum value in seconds, in order to give an answer for one card and will show the negative progress of how many more seconds are left to have time to answer this card.

The location of this additional line bar: directly above the "Life Drain", and the reverse report in seconds: at the beginning, on the left side.

Here is a picture of what I mean:
![Life Drain vers 2](https://user-images.githubusercontent.com/58599368/70330293-f75b7e80-1845-11ea-8977-3d07e8a55fad.png)

**Comment by Yutsuten** [comment]
I have a few questions in regard of your suggestion...

1. Is it a timer for individual cards like [Speed Focus Mode](https://ankiweb.net/shared/info/1046608507) does?
2. I still didn't get the point of the new bar. Why having it is better than not having?
3. Why having two life bars would make more sense than one?
4. If that bar has a bunch of new features, isn't that a new add-on (and not Life Drain anymore)? Some people may want only that feature and not Life Drain.

**Comment by niku-pal** [comment]
1. Yes, only made as a life bar.

2. & 3. 
Life Drain is already good, but with this addition I think it will be even better. One life bar for the whole deck, and one life bar for each card.
Like "Speed Focus Mode", this life bar will be train attention and increase the speed of learning.
You can also make several design options, for example, another one: 
As it decreases, the color changes, the full line of 100% - green, 50% - blue, 20% - red. Something like this.

4. Yes, you are right. It can be done as a new, separate add-on, but only so that it does not conflict with the Life Drain, it would be combined in colors and in terms of design.

**Comment by Yutsuten** [comment]
Your idea may be good, but it is out of the scope of what I proposed to do in my add-on. 
I prefer to focus on a single feature than trying to do everything.

In situations like this I remember the Unix philosophy:
> Do one thing and do it well.

You may install Speed Focus Mode and use it as it is. Or if you really want the bar, you may ask the Speed Focus Mode developer to add an option that does so.

Sorry... And thank you for the feedback and suggestion!

**Comment by niku-pal** [comment]
Thank you for your time.
Good luck and thanks again for Life Drain!
