### ISSUE TITLE
Allow configuring the shortcut keys

### ISSUE THREAD

**Issue by drmarmalademd** [Yutsuten/anki-lifedrain#49]
Not entirely an issue - but I also use speed focus mode which uses the shortcut "P" to pause, and with it enabled, I cannot pause life drain. Is there an easy way to change the shortcut or to make the shortcuts compatible? Thanks!

**Comment by Yutsuten** [comment]
Actually that's a very good suggestion. I think it would be great to allow users to change the shortcut. But its implementation will take some time.

For now, as it is directly affecting you, I'd recommend you to change the source code directly. It will be an easy change, you will just change a letter.

https://github.com/Yutsuten/anki-lifedrain/blob/a0b7dadf0157ea6743816237f5a7c0c31aa91369/lifedrain/lifedrain.py#L758-L765

You'll have to change the line `shortcuts.append(tuple(['p', toggleTimer]))`. Change the `p` with whatever key you want. Restart Anki and you should be done.

**Comment by drmarmalademd** [comment]
Awesome! That did the trick. Thanks!

**Comment by Yutsuten** [comment]
As I want the users to be able to fully configure their shortcuts, I've edited the title and objective of the issue to something more generic.

My plan is to add options for configuring the pause, deck settings and global settings shortcut keys.
