### ISSUE TITLE
[Feature Request] option to damage only on reviews

### ISSUE THREAD

**Issue by Mete0** [Yutsuten/anki-lifedrain#57]
Use case:
As a user, Id like to be able to disable damage when the card is new. That way I dont start losing alot of life when Im done with my reviews and am encountering alot of new cards.

**Comment by Yutsuten** [comment]
Thank you for the feedback about the damage feature!

Your feature request seems fair. We could separate card types "New", "Learning" and "To review" and apply damage only to the selected types.
This implementation will take some time, but I plan to do it.

**Comment by nekobusses** [comment]
As a user who has a more rapid drain implemented, 
Treating new cards differently seems necessary to keep the flow going while working through new cards.

However, to fit more use cases, new cards taking a different amount of damage (less or negative damage) than learning/review cards would be a better solution.

This way if you've set damage to zero for learning/review cards, 
you can set your new cards to a negative damage to refill your health bar and encourage more coverage of new cards.
