### ISSUE TITLE
June 3rd Update Bug

### ISSUE THREAD

**Issue by jamiekoi** [Yutsuten/anki-lifedrain#73]
Hi,
Most recent update gives this error when I open Anki:
I'm running Anki 2.1.23 and MacOS Catalina.

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> 
> When loading '⁨Life Drain⁩':
> ⁨Traceback (most recent call last):
>   File "aqt/addons.py", line 208, in loadAddons
>   File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/715575551/__init__.py", line 6, in <module>
>     from . import main
>   File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/715575551/main.py", line 24, in <module>
>     from lifedrain.lifedrain import Lifedrain
> ModuleNotFoundError: No module named 'lifedrain'

⁩

**Comment by Yutsuten** [comment]
I've updated a new release fixing this, can you check please?
Sorry for the trouble.

**Comment by jamiekoi** [comment]
Just updated, and now works!
Thanks for the speedy fix!

**Comment by Yutsuten** [comment]
No problem!
Thank you for reporting the issue!!
