### ISSUE TITLE
Share progress across multiple decks

### ISSUE THREAD

**Issue by spartandrew18** [Yutsuten/anki-lifedrain#87]
I want to use this addon primarily as a Pomodoro timer. Would it be possible for you to somehow have the life drain be synced to multiple decks? For example, If I have 3 different subdecks under the main deck and I set my max life to 50 minutes (3000 seconds), as soon as I start studying deck 1 the life starts draining. Now let's say at 2500 seconds I finished deck 1 and now want to move onto deck 2 with the timer still continuing where I left off from deck 1. So I click deck 2 to start studying and the life drains from 2500 seconds. Then at 2000 seconds, I want to move to deck 3 with the same principle.

Is this possible to tinker within the settings? If not, would you mind adding this option in a future release?

I appreciate your time for making such an awesome addon! I hope you are doing well!

Best,
Andrew

**Comment by Yutsuten** [comment]
Hello Andrew! Thank you for the feedback!

I see many ways to achieve what you want, but it will require some work from my side. Its not something that can be achieved with simple changes on the current source code.

The possibilities I see are:

1. Allow making the deck settings to be set globally, so any deck would share the same configuration and status.
2. Allow linking the deck settings with a option group (maybe was like that previously without I being aware...), so decks in that option group would share the configuration and status.

For me both seems to worth implementing, but both are huge changes. Which one seems to work better for you?

**Comment by spartandrew18** [comment]
Hi Yutsuten,

So I agree that both would be awesome to implement together! However, I think what might work best for my purposes right now is option 1. Ideally, I want lifedrain to work globally across all decks as one cohesive drain. I am a little confused about what you meant by the same configuration? I am guessing you're talking about the life drain options (ie. Maximum Life, Recover, Enable Damage, Damage, and Current Life) as being a global set option across all decks. I believe that would be fine. Another thing I was confused about was the mention of status? By status do you mean the progress of the life drain bar? Ideally, I want what you stated "so any deck would share the same configuration and status."

If what I stated above was hard to read let me try and give a scenario of what I would like to see when I open Anki with life drain.

1. I Open Anki and am at the home page
2. I click subdeck 1 out of 10 under the main deck. In this case, subdeck Biology under MilesDown main deck. My Lifedrain options are 3000 max life, 0 recover, no enable damage, 3000 current life.
3. I finish subdeck biology and my lifedrain bar is at 2500.
4. I click subdeck 2 out of 10 under the main deck. In this case, subdeck Chemistry under MilesDown main deck.
5. My life should be at 2500 when I start this deck. As soon as I finish chemistry I go to the next deck and the same principle applies.

Now I was thinking about some more intuitive options you could add on top of this if you are willing. When the global lifedrain hits 0, is it possible to add a switch to lifegain progress bar (basically opposite of draining life)? So I went from 3000 --> 0 which was 50 minutes of time studying and now I want my 10 minute break so as soon as I hit 0, the lifegain progress bar starts and loads to 100% or 600 seconds (10 mins).

After my gain of 10 minutes occurred and my progress bar is at the full 600 seconds I click to study the deck again and my life goes back to 3000, ready for another 50-minute session.

Lifegain could have the option of setting how long you want the lifegain to occur such as 10 minutes in my case, and also switching the color of the progress bar when it enters lifegain mode. So I have mine set to green in draining mode but as soon as I enter gaining mode lets say it turns white. This could be a picked color like you added for the background color option.

Finally, I have been trying to discuss with fanfare/gamification author to see if he could incorporate an intermission break with time instead of number of cards reviewed. That way when these 2 addons work together it makes an awesome pair.

So if I did 50 minutes of studying and my life drain hits 0 then fanfare would boot me into an intermission break while my lifegain is happening for 10 minutes. This way I know when to come back to studying!

**Comment by Yutsuten** [comment]
Sorry for my wording.

By "configuration" I meant Maximum Life, Recover, Enable Damage, Damage.
By "status" I meant Current Life.

So sharing globally those seems to be what you want.

---

About Lifegain, that may make sense when you're using it as a Pomodoro, but I'm not sure if it makes sense otherwise. I'll have to think more about this.

Not exactly the lifegain you explained, but I have plans to add a button / shortcut to recover life. See #52.

**Comment by spartandrew18** [comment]
Yeah, the lifegain was basically for the Pomodoro effect. Maybe you can have it as some kind of option in the menu?

I do get that this is probably not what you intended for on this addons use.

Thanks for the quick reply and I am looking forward to the changes!

Best,
Andrew

**Comment by Yutsuten** [comment]
Just a random idea I had now, but probably would be cool if the recover button had an option to recover instantly OR recover slowly until full life given a time set by the user in the settings.

**Comment by spartandrew18** [comment]
That actually sounds awesome! So my thinking is the user has control of when he wants the break to start rather than having it automatically kick in as soon as lifedrain hits 0!

So like if I wanted my life to start gaining for 10 minutes I hit the hotkey for it and it starts gaining. Making the gain progress with the suggestions I stated above I think would be outstanding!
