### ISSUE TITLE
global lifedrain as pomodoro

### ISSUE THREAD

**Issue by Laern2Do** [Yutsuten/anki-lifedrain#88]
dying for a pomodoro clock in anki... XD, 

can we have lifedrain implement beyond reviewing purpose? it would be nice to add an option to have it countdown(drain) in the main screen or that "waiting for editing to finish" screen when editing in the browser. 

aside from reviewing, I think it nice to have an idea of the overall time that I've spent working in anki

(i work with split screen so window wont overlap, visibility wont be an issue)

thanks!

**Comment by Yutsuten** [comment]
I was discussing about a global life bar on #87, I think that idea partially address what you're saying.

It is nice that people are using this add-on as a Pomodoro timer too, but I cannot lose the main focus of my add-on.

>The objective is to give a visual feedback of how fast the questions are being answered. If the life is low, it means that you are distracted or taking too much time to answer.

The focus of the add-on is to improve review times. Using the add-on as a Pomodoro probably adds some kind of pressure, so it's valid.

But what would be the advantage of having a drain while in the deck browser or overview screen? The feature must have a value to worth the implementation.

**Comment by Laern2Do** [comment]
i saw the #87 address, where it request for life drain to synch across decks but would still all under "during review only category". 

the advantage of having drain options with other screen is to have a pomodoro  section beyond just reviewing, e.g., adding new cards, fixing certain cards in the browser. a typical anki section include: adding, adjusting, reviewing, etc... but currently lifedrain only apply to "reviewing" portion of the process and does not capture overall time spend on anki as an effective pomodoro section. hence the suggestion, because at this point, there is no working pomoclock associate with anki.

i think lifedrain being double as a pomoclock is great, that why I thought to mention :), but completely understand ur principle of keeping "it is for what it is", in this case being a reviewer enhancer. 

thanks :)! and will close this
