### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tiffanyhclau** [Yutsuten/anki-lifedrain#94]
**Anki version & Operating System:** 2.1.23 on MacOS

**Describe the bug:** Missing Global Settings (not in Tools or Config section of addon)

**Comment by Yutsuten** [comment]
Have you read the documentation of the add-on on the wiki?
https://github.com/Yutsuten/anki-lifedrain/wiki/Global-Settings

**Comment by tiffanyhclau** [comment]
![image](https://user-images.githubusercontent.com/66158732/85201456-fe556480-b331-11ea-98b6-58366b14a020.png)

**Comment by tiffanyhclau** [comment]
Ah it's in Anki → Preferences, saw it thanks!

**Comment by Yutsuten** [comment]
Oh, so on Mac it is not `Tools > Preferences` but `Anki > Preferences`. I didn't know that...
Thank you for telling me, I'll add an observation for mac users about it on the wiki!
