### ISSUE TITLE
Change life bar color depending on % of life remaining

### ISSUE THREAD

**Issue by ayynonwhymouse** [Yutsuten/anki-lifedrain#98]
It would be fun if the bar had a color gradient or could change based on the % of life remaining, similar to how it appears in most video games. Something like this: [link](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/29399f7b-e4d8-4370-b051-a55691086964/d8e13ri-3c284269-78ef-4a3e-9b64-7dd837828dbe.png/v1/fill/w_1024,h_1472,strp/basic_health_bar_by_annariette_d8e13ri-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD0xNDcyIiwicGF0aCI6IlwvZlwvMjkzOTlmN2ItZTRkOC00MzcwLWIwNTEtYTU1NjkxMDg2OTY0XC9kOGUxM3JpLTNjMjg0MjY5LTc4ZWYtNGEzZS05YjY0LTdkZDgzNzgyOGRiZS5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.GI6Q9eucc_I-taPGSR_A9i3v5heL4YzJ5Xx9xAniwUA)

**Comment by Yutsuten** [comment]
Actually I was already thinking about adding something like this, so sure!

**Comment by Yutsuten** [comment]
Sorry for taking 3 years to implement it... :sweat: 

I will release it after implementing some other features.
